---
- name: Install dnf packages
  become: yes
  become_method: sudo
  dnf:
    pkg:
      - i3
      - polybar
      - feh
      - flameshot
      - arandr

- name: Import Microsoft key
  become: yes
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add Microsoft repository
  become: yes
  become_method: sudo
  copy:
    content: |
      [vscode]
      name=Visual Studio Code
      baseurl=https://packages.microsoft.com/yumrepos/vscode
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc
      repo_gpgcheck=1
    dest: /etc/yum.repos.d/vscode.repo

- name: Install Visual Studio Code
  become: yes
  dnf:
    name: code
    state: present

- name: Install VScode extensions
  command: code --install-extension {{ item }}
  register: vscode_extension_installation
  changed_when: "'already installed' not in vscode_extension_installation.stdout"
  loop:
    - adamhartford.vscode-base64
    - adpyke.vscode-sql-formatter
    - mechatroner.rainbow-csv
    - medo64.render-crlf
    - mrorz.language-gettext
    - ms-python.python
    - ms-python.vscode-pylance
    - shardulm94.trailing-spaces
    - wengerk.highlight-bad-chars
    - golang.Go
    - github.copilot

- name: Set up i3 config from template
  template:
    src: templates/i3config
    dest: /home/{{ ansible_user_id }}/.config/i3/config

- name: Set up polybar launch script from template
  template:
    src: templates/polybar-launch.sh
    dest: /home/{{ ansible_user_id }}/.config/polybar/launch.sh
    mode: '0755'

- name: Set up polybar config from template
  become: yes
  template:
    src: templates/polybar-config.ini
    dest: /etc/polybar/config.ini

- name: Change to finnish keyboard
  template:
    src: templates/locale.conf
    dest: /etc/locale.conf

- name: Set up wallpapers
  become: yes
  copy:
    src: templates/wallpapers
    dest: /home/{{ ansible_user_id }}/
    mode: '0755'

- name: Set up display script
  template:
    src: templates/set_displays.sh
    dest: /home/{{ ansible_user_id }}/set_displays.sh
    mode: '0755'
