---
- name: Install APT packages
  become: yes
  become_method: sudo
  apt:
    pkg:
      - network-manager
      - zsh
      - fzf
      - rxvt-unicode
      - bluetooth
      - pavucontrol
      - pulseaudio
      - pulseaudio-module-bluetooth
      - gcc
      - make
      - python3-pip
      - golang
      - libssl-dev # Python dependency
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - llvm
      - libsqlite3-dev # Python dependency


- name: Set ZSH as default shell
  become: yes
  user: shell=/bin/zsh name={{ansible_user_id}}

- name: Set up .zshrc from template
  template:
    src: templates/.zshrc
    dest: /home/{{ ansible_user_id }}/.zshrc

- name: Set up .zprofile from template
  template:
    src: templates/.zprofile
    dest: /home/{{ ansible_user_id }}/.zprofile

- name: Set up .gitconfig from template
  template:
    src: templates/.gitconfig
    dest: /home/{{ ansible_user_id }}/.gitconfig

- name: Disable networkd during boot and mask it
  become: yes
  ansible.builtin.systemd:
    name: systemd-networkd-wait-online.service
    enabled: no
    masked: yes

- name: Enable bluetooth
  become: yes
  ansible.builtin.systemd:
    name: bluetooth.service
    enabled: yes
    masked: no

- name: Creates directory
  file:
    path: /home/{{ ansible_user_id }}/projects/go/src
    state: directory
