---
- name: Install APT packages
  become: yes
  become_method: sudo
  apt:
    pkg:
      - network-manager
      - zsh
      - fzf
      - rxvt-unicode

- name: Set ZSH as default shell
  become: yes
  user: shell=/bin/zsh name={{ansible_user_id}}

- name: Set up .zshrc from template
  template:
    src: templates/.zshrc
    dest: /home/{{ ansible_user_id }}/.zshrc

- name: Set up .zprofile from template
  template:
    src: templates/.zprofile
    dest: /home/{{ ansible_user_id }}/.zprofile

- name: Set up .gitconfig from template
  template:
    src: templates/.gitconfig
    dest: /home/{{ ansible_user_id }}/.gitconfig
