---
- name: Install dnf packages
  become: yes
  become_method: sudo
  dnf:
    pkg:
      - zsh
      - neovim
      - fzf
      - bat
      - tmux

- name: Change to finnish keyboard
  become: yes
  template:
    src: templates/locale.conf
    dest: /etc/locale.conf

- name: Set login shell of user {{ ansible_env.USER }} to `/bin/zsh` with `usermod`
  command: usermod --shell /bin/zsh {{ ansible_env.USER }}
  become: true
  changed_when: false

- name: Set up zsh config
  template:
    src: templates/.zshrc
    dest: /home/{{ ansible_user_id }}/.zshrc

- name: Set up tmux config
  become: yes
  become_user: root
  copy:
    src: templates/.tmux.conf
    dest: /etc/.tmux.conf

- name: Clone TPM repository
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
